FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_PATIENT_API_URL
ARG VITE_COMMS_API_URL
ARG VITE_COMMS_OPERATOR_SECRET
ENV VITE_PATIENT_API_URL=$VITE_PATIENT_API_URL
ENV VITE_COMMS_API_URL=$VITE_COMMS_API_URL
ENV VITE_COMMS_OPERATOR_SECRET=$VITE_COMMS_OPERATOR_SECRET

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["sh", "-c", "serve -s dist -l ${PORT:-3000}"]
